version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: myDataWeb
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
